.storybook/preview-head.html, .storybook/preview.tsx, index.html, package.json, src/common/style/globalStyle.ts, src/common/style/theme/emotion.d.ts, src/common/style/theme/theme.ts, tsconfig.json
closed #7 
---
---
- index.html에서 link 태그를 통해 폰트 링크 첨부하는 거 잊지 말기
```typescript
type ButtonProps = ComponentPropsWithRef<'button'>;
const Button = ({ children }: ButtonProps) => {
return (
<button
css={{
...theme.heading.heading01, // font
color: theme.colors.blue_100, // color 
}}>
{children}
</button>
);
};
export default Button;
```
- 이런식으로 font와 color 지정 가능합니다.
- font는 heading, text, label 세 가지가 있습니다 !! 
---
- 로컬에서는 잘 실행되는데 storybook에서는 폰트 적용이 안되는 이슈가 있어요 ..
-> 해결 !!
- preview-head.html 를 .storybook 폴더 하위로 둬서 link 태그로 폰트 불러와줘서 해결했습니다!
```html
<link
rel="stylesheet"
href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.8/dist/web/variable/pretendardvariable.css" />
```
---
=> [feat] 스타일 가이드 세팅

src/common/component/Select/Select.style.ts, src/story/common/Select.stories.tsx
closed #30 
---
---
- `hover` 혹은 `focus` 시 색상이 변경되도록 구현
- 특정 height를 넘을 시 스크롤 되도록 구현
=> [Refactor] Select 컴포넌트 GUI에 따른 hover color, scroll 적용

.github/workflows/chromatic.yml, .gitignore, src/common/component/Header/Header.style.ts, src/common/component/Header/Header.tsx, src/story/common/Header.stories.tsx
=> #38 docs: 크로마틱 ci 스크립트 수정

src/common/component/Select/Select.style.ts, src/common/component/Text/Text.tsx, src/common/style/theme/theme.ts, src/common/type/design.ts, src/page/login/LoginPage.style.ts, src/shared/component/createWorkSpace/category/WorkSpaceCategory.tsx, src/story/common/Button.stories.tsx, src/story/common/Header.stories.tsx, src/story/common/Heading.stories.tsx, src/story/common/Input.stories.tsx, src/story/common/Text.stories.tsx, src/story/page/archiving/DaySection.stories.tsx
=> [Refactor] 컴포넌트 스토리 문서화 재정립

src/common/router/Router.tsx, src/shared/api/interceptor.ts, src/shared/component/Login/Login.tsx, src/shared/constant/path.ts
=> [Refactor] redirect PATH 및 라우터 수정

src/page/signUp/info/InfoFormPage.tsx, src/page/signUp/info/component/InfoForm/InfoForm.tsx, src/shared/api/mail/checking/index.ts, src/shared/api/mail/password/index.ts, src/shared/api/mail/signup/index.ts, src/shared/api/members/password/index.ts
=> [Fix] axiosInstance 에러 해결

vercel.json
=> [Docs] vercel https -> http

src/page/archiving/index/component/DocumentItem/DocumentItem.tsx, src/page/archiving/index/component/SelectedBlock/SelectedBlock.tsx, src/page/archiving/index/util/document.ts
closed #140
---
---
---
파일을 다운로드하는 방법에 대해 알게되었습니다.
```typescript
export const handleDownload = (fileUrl: string, name?: string) => {
const url = URL.createObjectURL(new Blob([fileUrl]));
const a = document.createElement('a');
a.href = url;
name && (a.download = name);
document.body.appendChild(a);
a.click();
setTimeout(() => {
window.URL.revokeObjectURL(fileUrl);
}, 1000);
a.remove();
};
```
파일의 url을 다룰때는 Blob() 타입으로 받아와 줘야 합니다! 
---
=> [Feat] 파일 다운로드 기능 딸깍

src/page/archiving/createTimeBlock/component/Upload/UploadModal.tsx, src/page/archiving/createTimeBlock/constant/iconBlock.tsx
=> [refactor] 모달 TASK 오류 수정

src/common/component/Select/Select.tsx, src/common/style/globalStyle.ts, src/common/style/theme/scroll.ts, src/page/archiving/index/ArchivingPage.tsx, src/page/archiving/index/component/DaySection/DaySection.tsx, src/page/archiving/index/component/DocumentBar/DocumentBar.tsx, src/page/archiving/index/component/MonthHeader/MonthHeader.style.ts, src/page/archiving/index/component/MonthHeader/MonthHeader.tsx, src/page/archiving/index/component/SelectedBlock/SelectedBlock.tsx, src/page/archiving/index/component/TimeBlock/TimeBlock.tsx, src/page/showcase/index/ShowcasePage.tsx, src/page/signUp/index/TermPage.tsx, src/page/signUp/info/component/InfoForm/InfoForm.tsx, src/page/signUp/info/hook/common/useDateInput.ts, src/page/signUp/info/hook/common/useTimer.ts, src/story/page/archiving/MonthHeader.stories.tsx
=> [Hotfix] Timeline 블록 선택 에러 해결, 회원가입 로직 디벨롭

src/page/archiving/index/component/TotalDocument/TotalDocument.tsx, src/shared/component/LeftSidebar/LeftSidebar.style.ts, src/shared/component/LeftSidebar/LeftSidebar.tsx, src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarItem.style.ts, src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarItem.tsx, src/shared/constant/index.ts
=> [Fix] 레싸바 오류 해결

src/page/archiving/index/ArchivingPage.tsx, src/page/archiving/index/util/block.ts
=> [Fix] 타임 블록 달 겹치는 경우 쌓기

src/page/archiving/index/ArchivingPage.style.ts, src/page/archiving/index/component/DaySection/DaySection.style.ts, src/page/archiving/index/component/DaySection/DaySection.tsx, src/page/archiving/index/component/TimeBlock/TimeBlock.style.ts, src/page/archiving/index/component/YearHeader/YearHeader.tsx
=> [Hotfix] TimeLine 뷰 QA

src/App.tsx
=> [refactor]레이아웃 수정

.github/workflows/automatic-aws-deployment.yml, .github/workflows/chromatic.yml
closed #193
---
---
```yml
name: 'Automatic S3 Cloudfront Deployment'
on:
push:
branches: # main에 push되었을 때 트리거
- main
pull_request: # develop에 pr이 생성되었을 때 트리거
branches:
- develop
jobs:
cicd:
name: Build and Deploy
runs-on: ubuntu-latest
steps:
- name: Checkout # 레포지토리 체크아웃 (저장소로부터 코드 내려받음)
uses: actions/checkout@v3
- name: Setup Node.js # node.js 세팅
uses: actions/setup-node@v4
with:
node-version: 21
- name: Setup pnpm # pnpm 세팅
uses: pnpm/action-setup@v4
with:
version: 9
- name: Install dependencies and build # 의존성 설치 후 빌드
run: pnpm install --frozen-lockfile && pnpm build
- name: Configure AWS credentials # GitHub env(secrets 값)을 통해 AWS 연동
uses: aws-actions/configure-aws-credentials@v1
with:
aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
aws-secret-access-key: ${{ …
```
=> [Docs] s3 cloudfront ci cd workflow

.github/workflows/chromatic.yml, src/page/archiving/index/ArchivingPage.tsx, src/story/common/Modal.stories.tsx
closed #224 
---
---
`thollander/actions-comment-pull-request` 깃헙 액션을 사용하면, 특정 브랜치로 `pr`이 트리거되었을 때, `message`와 함께 코멘트를 남길 수 있습니다.
이를 통해, 특정 컴포넌트의 스토리를 생성하여 PR을 올렸을 시 크로마틱을 통해 자동 배포되고, 이에 대한 Build + Preview를 확인할 수 있는 코멘트를 남기도록 설정하였습니다.
=> [Docs] Storybook Build, Preview CI Script

src/App.tsx, src/common/component/Button/Button.style.ts, src/common/component/DatePicker/Calendar/Calendar.style.ts, src/common/component/Input/Input.style.ts, src/common/component/Select/Select.style.ts, src/common/component/Spinner/Spinner.tsx, src/common/component/SupportingText/SupportingText.style.ts, src/common/component/Tab/style.ts, src/common/style/theme/theme.ts, src/page/archiving/index/ArchivingPage.style.ts, src/page/archiving/index/component/DaySection/DaySection.tsx, src/page/archiving/index/component/MonthHeader/MonthHeader.style.ts, src/page/archiving/index/component/TimeBlockModal/component/Block/Icon/BlockIcon.style.ts, src/page/landing/component/Overview/Overview.style.ts, src/page/login/password/auth/PasswordAuthPage.style.ts, src/page/login/password/reset/PasswordResetPage.style.ts, src/page/showcase/index/component/AdvBanner/AdvBanner.style.ts, src/page/showcase/index/component/CategoryChip/CategoryChip.style.ts, src/page/signUp/index/component/TermArea/TermArea.tsx, src/page/signUp/index/component/TermsAgreeButton/TermsAgreeButton.style.ts, src/page/signUp/info/InfoFormPage.style.ts, src/page/signUp/info/component/InfoForm/InfoForm.style.ts, src/shared/component/DeleteModal/DeleteModal.style.ts, src/shared/component/LeftSidebar/LeftSidebar.style.ts, src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarMenuItem.style.ts, src/shared/component/LeftSidebar/LeftSidebarItem/PageIndicatorStick/PageIndicatorStick.style.ts, src/shared/component/WorkSpaceModal/category/WorkSpaceCategory.style.ts, src/shared/component/WorkSpaceModal/image/WorkSpaceImage.style.ts, src/shared/component/WorkSpaceModal/name/WorkSpaceName.style.ts, src/story/page/archiving/TimeBlock.stories.tsx
closed #255 
---
---
key_600
key_500
key_200
key_100
red_200
red_100
yellow_200
yellow_100
green_200
green_100
blue_200
blue_100
pink_200
pink_100
sky_200
sky_100
body10
---
---
=> [Init] color, font 수정 사항 반영

src/common/component/CheckBox/CheckBox.style.ts, src/common/component/CheckBox/CheckBox.tsx, src/story/common/CheckBox.stories.tsx
closed #278 
---
---
단순 퍼블리싱이였습니다 !
`checked` 상태와 `onChange` 핸들러를 받아 그에 맞게 체크 상태를 표시/변경 하도록 하였습니다.
---
=> [Feat] Checkbox 컴포넌트 퍼블리싱

src/common/component/Menu/MenuItem/MenuItem.style.ts, src/common/component/Menu/MenuItem/MenuItem.tsx, src/common/component/Menu/MenuList/MenuList.style.ts, src/common/component/Menu/MenuList/MenuList.tsx, src/shared/component/SideNavBar/LeftSidebar.tsx, src/story/common/MenuList.stories.tsx
closed #286 
---
---
--- 새로운 메뉴의 variant가 생겼길래 얼른 적용해봤습니다! 
아래의 사진처럼 생긴 것들이 메뉴입니다!
스토리북 참고부탁드립니다!
=> [Feat] menu 공통 컴포넌트 GUI 업데이트

.github/workflows/storybook-deploy.yml
=> [Deployment] Storybook GitHub pages 배포

package.json, pnpm-lock.yaml, src/mock/data/drive.ts, src/shared/component/ContentBox/ContentBox.style.ts
closed #308
---
---
기존에는 `Content Box`의 가장 위 컨테이너인 `section` 부분에 `minHeight`와 `height`를 둘 다 선언해주었는데, 이러니까 스크롤이 끝까지 안되는 문제를 보운님께서 발견해주셨습니다 .. ! 그래서 `section`부분은 `minHeight`만을 주되, 실제로 `children`으로 들어가는 컨텐츠 부분의 높이를 계산하여 지정해주었어요 ! 이제 스크롤 끝까지 잘되네용
---
https://github.com/user-attachments/assets/84aef400-0cc5-4d1d-9bcb-5e881c6b0770
=> [Fix] Content Box 스크롤 이슈 해결

apps/client/vite.config.ts
=> [FIX] UI package resolve alias 추가

apps/client/vite.config.ts
=> [Fix] Vite config Icon deps, alias 추가

apps/client/vercel.json
=> [Docs] QA용 버셀 프로덕션 배포를 위한 vercel json 추가

apps/client/vite.config.ts
=> [Docs] Vite config rollupOptions 제외 불필요 속성 삭제

apps/client/src/shared/__generated__/schema.d.ts, apps/client/src/shared/component/InviteModal/InviteModal.style.ts, apps/client/src/shared/component/InviteModal/InviteModal.tsx
closed #396 
---
---
배열에 이메일 담고 반복문 사용해서 Mutate 함수 호출했습니다.
---
---
=> [Feat] 초대 메일 전송 api 연결

apps/client/src/shared/component/Header/InviteButton.tsx, apps/client/src/shared/component/InviteModal/InviteModal.style.ts, apps/client/src/shared/component/InviteModal/InviteModal.tsx, apps/client/src/shared/component/InviteModal/Member/MemberItem.style.ts, apps/client/src/shared/component/InviteModal/Member/MemberItem.tsx, apps/client/src/shared/component/Modal/Footer/ModalFooter.tsx, apps/client/src/shared/component/Modal/ModalFunnel.tsx, apps/client/src/shared/constant/modal.tsx
closed #454
---
팀원 초대 모달 스타일 이상한 부분들 살짝 고치고 핸들러 연결 했슴다 ~!
---
=> [Feat] 팀원 초대 모달 연결

apps/client/src/page/archiving/index/ArchivingPage.style.ts, apps/client/src/page/archiving/index/component/TimeLine/TimeLineHeader/TimeLineHeader.style.ts, apps/client/src/page/archiving/index/component/TimeLine/TimeLineHeader/TimeLineHeader.tsx
closed #478 
---
---
---
간단한 스타일 큐에이 입니다 !
---
=> [Fix] 타임라인 QA 해결

apps/client/src/page/signUp/index/component/TermItem/TermItem.style.ts, apps/client/src/page/signUp/index/component/TermItem/TermItem.tsx, apps/client/src/page/signUp/index/component/TermsAgreeButton/TermsAgreeButton.style.ts, apps/client/src/page/signUp/info/InfoFormPage.style.ts, apps/client/src/page/signUp/info/InfoFormPage.tsx, apps/client/src/page/signUp/info/UnivFormPage.tsx, apps/client/src/page/signUp/info/hook/common/useInfoForm.ts, apps/client/src/shared/api/client.ts, apps/client/src/shared/api/signup/info/type.ts, apps/client/src/shared/constant/form.ts, packages/ui/src/Select/Select.style.ts, packages/utils/src/hooks/useTimer.ts
closed #484 
---
---
디자인 QA 진행하였습니다. 회원가입 정상화, 디테일한 css, 폼 유효성 검사 로직 등등 수정해주었습니다.
---
=> [Refactor] 약관동의/회원가입 디자인 QA

apps/client/src/page/login/index/LoginPage.style.ts, apps/client/src/page/login/index/LoginPage.tsx, apps/client/src/page/login/index/hook/useLoginMutation.ts
closed #480 
---
---
디자인 QA 진행하였습니다.
로그인 페이지 들어갔을 때 바로 `email` 인풋이 포커스될 수 있도록 하였습니다. 이 부분은 디자이너와 합의 후 결정하였습니다.
다른 건 사소한 스타일들 수정입니다 !
=> [Refactor] 로그인 페이지 디자인 QA

package.json, pnpm-lock.yaml
=> [Refactor] Lottie react 버전 픽스

apps/client/src/page/drive/component/FileListHeader/FileListHeader.style.ts, apps/client/src/page/drive/component/FileListItem/FileListItem.style.ts, apps/client/src/page/drive/component/FileListItem/FileListItem.tsx, apps/client/src/page/drive/component/FileListItem/FolderListItem.tsx, apps/client/src/page/drive/index.style.ts, apps/client/src/page/drive/index.tsx, apps/client/src/shared/component/FileGrid/FileGrid.tsx, apps/client/src/shared/component/FileGrid/index.style.ts, apps/client/src/shared/util/file.ts, apps/client/src/story/page/drive/FileListItem.stories.tsx, packages/utils/src/hooks/useDeferedSearchFilter.ts
closed #492
---
---
드라이브 페이지 QA 진행하였습니다. 대부분 자잘한 스타일 수정이였어요 !
---
- 그리드 너비 고정 + column 6 추가
https://github.com/user-attachments/assets/ab4bbe3f-64d0-4328-b337-c971d88a8923
- 목록 뷰 디바이더 추가
=> [Fix] 드라이브 페이지 QA
